# This file configures the static analysis results for your project (errors,
# warnings, and lints).
#
# This enables the 'recommended' set of lints from `package:lints`.
# This set helps identify many issues that may lead to problems when running
# or consuming Dart code, and enforces writing Dart using a single, idiomatic
# style and format.
#
# If you want a smaller set of lints you can change this to specify
# 'package:lints/core.yaml'. These are just the most critical lints
# (the recommended set includes the core lints).
# The core lints are also what is used by pub.dev for scoring packages.

include: package:lints/recommended.yaml
  

analyzer:
  errors:
    constant_identifier_names: ignore
    file_names: ignore
    must_be_immutable: ignore


linter:
  rules:
    non_constant_identifier_names: false
    sort_child_properties_last: false
    use_build_context_synchronously: false
    constant_identifier_names: false
    file_names: false
    unnecessary_this: false
    camel_case_types: false
    library_prefixes: false